### PR TITLE
Backport rsync and xxhash for XCode 12

### PR DESCRIPTION
**Pull request by dennisklein**
`rsync@3.1.3` fails on XCode12 with:

```
/Users/alfaci/dklein/FairSoft/spack/lib/spack/env/clang/clang -I. -I/var/folders/br/qb161df93wzg0hwrzx48580c0000gp/T/alfaci/spack-stage/spack-stage-rsync-3.1.3-vhtbwpezoq4oa5jitvpr3njktomfxfbf/spack-src -g -O2 -DHAVE_CONFIG_H -Wall -W  -c lib/compat.c -o lib/compat.o
In file included from lib/compat.c:22:
./rsync.h:1035:9: warning: 'vsnprintf' macro redefined [-Wmacro-redefined]
#define vsnprintf rsync_vsnprintf
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/secure/_stdio.h:74:9: note: previous definition is here
#define vsnprintf(str, len, format, ap) \
        ^
In file included from lib/compat.c:22:
./rsync.h:1040:9: warning: 'snprintf' macro redefined [-Wmacro-redefined]
#define snprintf rsync_snprintf
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/secure/_stdio.h:56:9: note: previous definition is here
#define snprintf(str, len, ...) \
        ^
lib/compat.c:154:24: error: too few arguments to function call, expected 2, have 1
        return gettimeofday(tv);
               ~~~~~~~~~~~~   ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/time.h:197:1: note: 'gettimeofday' declared here
int     gettimeofday(struct timeval * __restrict, void * __restrict);
^
2 warnings and 1 error generated.
make: *** [lib/compat.o] Error 1
==> Error: ProcessError: Command exited with status 2:
    'make'
```

### CODE REVIEW

**Review by ChristianTackeGSI — APPROVED** [review]
Looks good.

Do you want to add a quick commit on the lines
```diff
-Integer our_quiet_period = 600;
+Integer our_quiet_period = 3 * 3600;
```
for Jenkinsfile?

**Comment by dennisklein** [comment]
> Looks good.
> 
> Do you want to add a quick commit on the lines
> 
> ```diff
> -Integer our_quiet_period = 600;
> +Integer our_quiet_period = 3 * 3600;
> ```
> 
> for Jenkinsfile?

done

**Review by ChristianTackeGSI — APPROVED** [review]

**Comment by dennisklein** [comment]
hm, macOS builds on citmac001 (Python 3.8.5) are stuck in endless loop on `==> Installing openblas in progress by another process` similar to what @MohammadAlTurany is seeing on his laptop. I triggered a build without ctest parallelism, let's see.

**Comment by dennisklein** [comment]
The `openblas` build errors we see, are already reported without solution yet: https://github.com/spack/spack/issues/19041 and https://github.com/spack/spack/issues/18658.

**Review by ChristianTackeGSI — APPROVED** [review]
Looks good, please merge.

**Comment by ChristianTackeGSI** [comment]
The one CI error are failing unit tests of FairRoot in the workflow.
(They're not Geant3 related, and do not look like timeouts. So they're possibly intersting. But they're orthogonal to the fixes in this PR.)
